# include: package:lint/analysis_options.yaml
include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    undefined_hidden_name: false
linter:
  rules:
    avoid_slow_async_io: true
    cancel_subscriptions: true
    cascade_invocations: true
    close_sinks: true
    curly_braces_in_flow_control_structures: false
    directives_ordering: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    join_return_with_assignment: true
    list_remove_unrelated_type: true
    omit_local_variable_types: false
    prefer_const_declarations: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_spread_collections: true
    sized_box_for_whitespace: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_lambdas: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    use_key_in_widget_constructors: true
    use_named_constants: true
    use_string_buffers: true
