include: package:pedantic/analysis_options.yaml
analyzer:
  errors:
    undefined_hidden_name: false
linter:
  rules:
    omit_local_variable_types: false
    curly_braces_in_flow_control_structures: false