name: churchdata
description: null

publish_to: "none"
version: 8.0.0+8

environment:
  sdk: ">=2.15.0 <3.0.0"

dependency_overrides:
  # firebase_database: ^8.0.0
  provider: ^6.0.1

dependencies:
  android_alarm_manager_plus: ^2.0.3
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.4
  cloud_functions: ^3.2.3
  connectivity_plus: ^2.1.0
  cupertino_icons: ^1.0.4
  device_info_plus: ^3.1.1
  disable_battery_optimization:
    git:
      url: https://github.com/Andrew-Bekhiet/disable_battery_optimization
      ref: e0bd4a6dc0ed3e411beb822a31b29e331416df86
  expandable: ^5.0.1
  feature_discovery: ^0.14.1
  file_picker: ^4.2.7
  firebase_analytics: ^9.0.2
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  firebase_crashlytics: ^2.4.3
  firebase_database: ^9.0.2
  firebase_dynamic_links: ^4.0.2
  firebase_in_app_messaging: ^0.6.0+4
  firebase_messaging: ^11.2.3
  firebase_remote_config: ^1.0.2
  firebase_storage: ^10.2.3
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.2
  flutter_contacts: ^1.1.1+2
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^9.1.5
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.3.2
  google_sign_in: ^5.2.1
  hive_flutter: ^1.1.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  local_auth: ^1.1.8
  location: ^4.3.0
  open_file: ^3.2.1
  package_info_plus: ^1.3.0
  path_provider: ^2.0.8
  percent_indicator: ^3.4.0
  permission_handler: ^8.3.0
  photo_view: ^0.13.0
  pie_chart: ^5.1.0
  pointycastle: ^3.4.0
  provider: ^6.0.1
  rxdart: ^0.27.3
  share_plus: ^3.0.4
  spreadsheet_decoder: ^2.0.0
  syncfusion_flutter_charts: ^19.3.57
  timeago: ^3.1.0
  tinycolor2: ^2.0.0
  tuple: ^2.0.0
  tutorial_coach_mark: ^1.2.0
  url_launcher: ^6.0.17
  version: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.5
  fake_cloud_firestore: ^1.2.0
  firebase_auth_mocks: ^0.8.1
  # TODO: mocks
  # firebase_database_mocks: ^0.2.0+1
  firebase_storage_mocks: ^0.5.0
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.12.0
  google_sign_in_mocks: ^0.2.1
  integration_test:
    sdk: flutter
  mockito: ^5.0.16

flutter_icons:
  image_path: "Logo.png"
  adaptive_icon_foreground: "Logo-Anniversary.png"
  adaptive_icon_background: "background.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MaterialIconsR
      fonts:
        - asset: fonts/MaterialIcons-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
