name: churchdata
description: null

publish_to: "none"
version: 8.0.0+8

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  battery_optimization:
    git:
      url: git://github.com/ChangJoo-Park/battery_optimization.git
      ref: master
  tinycolor:
    git:
      url: git://github.com/lslv1243/tinycolor.git
      ref: master
  android_alarm_manager_plus: ^1.0.2
  cached_network_image: ^3.0.0
  cloud_firestore: ^2.3.0
  cloud_functions: ^2.0.0
  connectivity_plus: 1.0.3
  cupertino_icons: ^1.0.3
  datetime_picker_formfield: ^2.0.0
  device_info_plus: ^2.0.1
  expandable: ^5.0.1
  feature_discovery: ^0.14.0
  file_picker: ^3.0.3
  firebase: ^9.0.1
  firebase_analytics: ^8.1.2
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.7
  firebase_database: ^7.1.1
  firebase_dynamic_links: ^2.0.6
  firebase_in_app_messaging: ^0.5.0+6
  firebase_messaging: ^10.0.3
  firebase_remote_config: 0.10.0+2
  firebase_storage: ^9.0.0
  flutter_colorpicker: ^0.4.0
  flutter_contacts: ^1.1.0+3
  flutter_dotenv: ^5.0.0
  flutter_local_notifications: ^6.0.0
  flutter_secure_storage: ^4.2.0
  flutter_stream_notifiers: ^0.3.0-nullsafety.0
  google_maps_flutter: ^2.0.6
  google_maps_flutter_web: ^0.3.0+2
  google_sign_in: ^5.0.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.1+3
  local_auth: ^1.1.6
  location: ^4.3.0
  open_file: ^3.2.1
  package_info_plus: ^1.0.3
  path_provider: ^2.0.2
  percent_indicator: 3.3.0-nullsafety.1
  permission_handler: ^8.1.2
  photo_view: ^0.11.1
  pie_chart: ^5.0.0
  pointycastle: ^3.1.3
  provider: ^5.0.0
  rxdart: ^0.27.1
  share_plus: ^2.1.4
  spreadsheet_decoder: ^2.0.0
  syncfusion_flutter_charts: ^19.2.44+1
  timeago: ^3.1.0
  tuple: ^2.0.0
  url_launcher: ^6.0.8
  version: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  pedantic: ^1.11.1

flutter_icons:
  image_path: "Logo.png"
  adaptive_icon_foreground: "Logo-Anniversary.png"
  adaptive_icon_background: "background.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MaterialIconsR
      fonts:
        - asset: fonts/MaterialIcons-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
