name: churchdata
description: null

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 6.3.3+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  android_alarm_manager_plus: ^1.0.0
  battery_optimization: ^0.1.0
  cached_network_image: ^3.0.0-nullsafety
  cloud_firestore: ^1.0.1
  cloud_functions: ^1.0.0
  connectivity_plus: ^1.0.0
  cupertino_icons: ^1.0.2
  datetime_picker_formfield: ^2.0.0
  device_info_plus: ^1.0.0
  expandable: ^4.1.4
  feature_discovery: ^0.13.0+2
  file_picker: ^3.0.0-nullsafety.4
  firebase: ^9.0.0
  firebase_analytics: ^7.1.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  firebase_crashlytics: ^1.0.0
  firebase_database: ^6.1.0
  firebase_dynamic_links: ^0.8.0
  firebase_in_app_messaging: ^0.4.0
  firebase_messaging: ^9.0.0
  firebase_remote_config: ^0.9.0-dev.0
  firebase_storage: ^8.0.0
  flutter_colorpicker: ^0.4.0-nullsafety.0
  flutter_contacts: ^0.3.3
  flutter_local_notifications: ^5.0.0-nullsafety.0
  flutter_secure_storage: ^4.1.0
  flutter_stream_notifiers: ^0.3.0-nullsafety.0
  google_maps_flutter: ^2.0.1
  google_sign_in: ^5.0.0
  google_maps_flutter_web: ^0.2.1
  hive: ^2.0.0
  hive_flutter: ^1.0.0-nullsafety.0
  icon_shadow: ^1.0.1
  image_cropper: ^1.4.0
  image_picker: ^0.7.2+1
  local_auth: ^1.1.0
  location: ^4.1.1
  open_file: ^3.1.0
  package_info_plus: ^1.0.0
  path_provider: ^2.0.1
  permission_handler: ^6.0.1+1
  photo_view: ^0.11.1
  pointycastle: ^3.0.0-nullsafety.2
  provider: ^4.3.3
  rxdart: ^0.26.0-nullsafety.1
  share_plus: ^2.1.0-nullsafety.0
  spreadsheet_decoder: ^2.0.0
  timeago: ^3.0.2
  tinycolor: ^1.0.3
  tuple: ^2.0.0-nullsafety.0
  url_launcher: ^6.0.2
  version: ^2.0.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  pedantic: ^1.11.0

flutter_icons:
  image_path: "Logo.png"
  adaptive_icon_foreground: "Logo-Anniversary.png"
  adaptive_icon_background: "background.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MaterialIconsR
      fonts:
        - asset: fonts/MaterialIcons-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
