name: churchdata
description: null

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.11.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  battery_optimization: ^0.1.0
  cached_network_image: ^2.3.3
  cloud_firestore: ^0.14.4
  cloud_functions: ^0.7.2
  connectivity: ^2.0.1
  cupertino_icons: ^1.0.0
  excel: ^1.1.5
  expandable: ^4.1.4
  file_picker: ^2.0.12
  firebase: ^7.3.2
  firebase_analytics: ^6.1.0
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_crashlytics: ^0.2.4
  firebase_database: ^4.4.0
  firebase_dynamic_links: ^0.6.3
  firebase_in_app_messaging: ^0.2.3
  firebase_messaging: ^7.0.3
  firebase_remote_config: ^0.4.3
  firebase_storage: ^5.2.0
  flutter_colorpicker: ^0.3.4
  flutter_contact: ^0.6.4
  flutter_launcher_icons: ^0.8.1
  flutter_phone_state: ^0.5.9
  flutter_secure_storage: ^3.3.5
  google_maps_flutter: ^1.0.6
  google_maps_flutter_web: ^0.1.0+7
  google_sign_in: ^4.5.6
  http: ^0.12.2
  icon_shadow: ^1.0.1
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+12
  local_auth: ^0.6.3+4
  location: ^3.0.2
  open_file: ^3.0.3
  package_info_plus: ^0.5.0
  path_provider: ^1.6.24
  permission_handler: ^5.0.1+1
  photo_view: ^0.10.2
  provider: ^4.3.2+2
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  spreadsheet_decoder: ^1.2.0
  steel_crypt: ^2.2.2+1
  syncfusion_flutter_xlsio: ^18.3.50-beta
  timeago: ^2.0.28
  tinycolor: ^1.0.3
  tuple: ^1.0.3
  url_launcher: ^5.7.10
  version: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "Logo.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MaterialIconsR
      fonts:
        - asset: fonts/MaterialIcons-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
